version: '3'
services:
  serverbase:
    container_name: serverbase
    build:
      context: ./server
      dockerfile: ./Dockerfileserverbase
  server:
    depends_on:
      - serverbase
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfileserver
    ports:
      - '5111:5111'
      - '8000:8000'
    restart: always

  clientbase:
    container_name: clientbase
    build:
      context: ./client
      dockerfile: ./Dockerfileclientbase
  client:
    depends_on:
      - clientbase
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfileclient
    ports:
      - '4200:4200'
      - '5110:80'
    restart: always
